name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - kb

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Forwarding
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: dan
          script: |
            export SSH_AUTH_SOCK=$(ls /tmp/ssh-*/agent.* | head -n 1)
            cd /var/www/html/docs
            git pull origin kb
            npm install
            npm run build
